services:
  bommanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bommanager
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=192.168.31.122
      - DB_PORT=3306
      - DB_USER=bommanager_admin
      - DB_PASSWORD=Hm7dgJ5ggHKebPM8
      - DB_NAME=bommanager_dev
      - MEDIA_BASE_URL=/media
      - MEDIA_DIR=/app/media
    volumes:
      - ./media:/app/media

