<template>
  <!-- Main iBOM Import Dialog -->
  <v-dialog
    :model-value="modelValue"
    max-width="1560"
    width="96vw"
    persistent
    scrollable
    @update:model-value="$emit('update:modelValue', $event)"
  >
    <v-card class="rounded-0 border bg-white d-flex flex-column" style="max-height: 92vh;">
      <!-- Dialog Header -->
      <v-card-item class="bg-slate-50 py-3 px-5 border-b flex-shrink-0">
        <div class="d-flex align-center justify-space-between">
          <div class="d-flex align-center">
            <v-icon color="primary" class="me-2">mdi-database-import-outline</v-icon>
            <div>
              <div class="text-subtitle-1 font-weight-bold text-slate-900">
                Import KiCAD Interactive HTML BOM (iBOM)
              </div>
              <div class="text-caption text-disabled">
                Project: {{ projectName || `Project #${projectId}` }}
              </div>
            </div>
          </div>

          <v-btn icon="mdi-close" variant="text" size="small" @click="closeDialog" />
        </div>
      </v-card-item>

      <!-- Dialog Body -->
      <v-card-text class="pa-0 flex-grow-1 overflow-y-auto">
        <!-- STEP 1: Select or Upload iBOM File -->
        <div v-if="currentStep === 1" class="pa-6">
          <div class="text-subtitle-1 font-weight-bold text-slate-900 mb-2">
            1. Select KiCAD iBOM HTML File
          </div>
          <p class="text-body-2 text-slate-600 mb-4">
            Upload an <code class="bg-slate-100 px-1 py-0.5 rounded font-mono">ibom.html</code> file generated by the KiCAD Interactive HTML BOM plugin, or select one from this project's existing attachments.
          </p>

          <v-row>
            <!-- Option A: Pick from project attachments if any available -->
            <v-col cols="12" md="6" v-if="ibomAttachments.length > 0">
              <v-card elevation="0" class="border rounded-0 pa-4 h-100 bg-slate-50">
                <div class="d-flex align-center mb-2">
                  <v-icon color="success" class="me-2">mdi-folder-open-outline</v-icon>
                  <span class="font-weight-bold text-subtitle-2 text-slate-900">From Attached Files</span>
                </div>
                <div class="text-caption text-slate-600 mb-3">
                  Select an iBOM file already attached to this project:
                </div>

                <v-select
                  v-model="selectedAttachmentId"
                  :items="ibomAttachments"
                  item-title="originalName"
                  item-value="id"
                  placeholder="Select attached iBOM file..."
                  variant="outlined"
                  density="comfortable"
                  class="bg-white mb-2"
                />

                <v-btn
                  color="primary"
                  variant="flat"
                  size="small"
                  class="font-weight-bold w-100"
                  prepend-icon="mdi-file-find-outline"
                  :disabled="!selectedAttachmentId"
                  :loading="parsing"
                  @click="parseSelectedAttachment"
                >
                  Analyze & Map Components
                </v-btn>
              </v-card>
            </v-col>

            <!-- Option B: Upload new file directly -->
            <v-col cols="12" :md="ibomAttachments.length > 0 ? 6 : 12">
              <v-card elevation="0" class="border rounded-0 pa-4 h-100 bg-slate-50">
                <div class="d-flex align-center mb-2">
                  <v-icon color="primary" class="me-2">mdi-upload</v-icon>
                  <span class="font-weight-bold text-subtitle-2 text-slate-900">Upload New iBOM File</span>
                </div>
                <div class="text-caption text-slate-600 mb-3">
                  Upload an <code class="font-mono">.html</code> file from your computer:
                </div>

                <v-file-input
                  v-model="uploadFile"
                  accept=".html,.htm"
                  label="Choose ibom.html file"
                  variant="outlined"
                  density="comfortable"
                  prepend-icon="mdi-paperclip"
                  class="bg-white mb-2"
                  show-size
                />

                <v-btn
                  color="primary"
                  variant="flat"
                  size="small"
                  class="font-weight-bold w-100"
                  prepend-icon="mdi-file-find-outline"
                  :disabled="!uploadFile"
                  :loading="parsing"
                  @click="parseUploadedFile"
                >
                  Analyze & Map Components
                </v-btn>
              </v-card>
            </v-col>
          </v-row>
        </div>

        <!-- STEP 2: Review and Map Components -->
        <div v-else-if="currentStep === 2" class="d-flex flex-column h-100">
          <!-- Board Metadata Banner -->
          <div class="bg-slate-50 px-5 py-3 border-b d-flex flex-wrap align-center justify-space-between gap-3">
            <div class="d-flex align-center flex-wrap gap-2">
              <span class="font-weight-bold text-slate-900 me-2 text-subtitle-1">
                {{ parseResult?.metadata?.title || 'KiCAD Board' }}
              </span>
              <v-chip size="small" color="secondary" variant="tonal" v-if="parseResult?.metadata?.revision">
                Rev: {{ parseResult.metadata.revision }}
              </v-chip>
              <v-chip size="small" color="primary" variant="flat" class="font-weight-bold">
                {{ mappedItems.length }} Part Groups
              </v-chip>
              <v-chip size="small" color="info" variant="tonal">
                {{ parseResult?.totalQuantity || 0 }} pcs total
              </v-chip>
              <span class="text-caption text-slate-500 ms-2" v-if="parseResult?.metadata?.date">
                Date: {{ parseResult.metadata.date }}
              </span>
            </div>

            <!-- Import Mode Selector -->
            <div class="d-flex align-center gap-3">
              <span class="text-caption font-weight-bold text-slate-700">Import Mode:</span>
              <v-btn-toggle
                v-model="importMode"
                mandatory
                density="compact"
                variant="outlined"
                color="primary"
                rounded="0"
              >
                <v-btn value="append" size="small" class="font-weight-medium">
                  <v-icon start size="14">mdi-plus</v-icon>
                  Append to BOM
                </v-btn>
                <v-btn value="replace" size="small" class="font-weight-medium text-error">
                  <v-icon start size="14">mdi-refresh</v-icon>
                  Replace BOM
                </v-btn>
              </v-btn-toggle>
            </div>
          </div>

          <!-- Mapping Toolbar & Quick Actions -->
          <div class="px-5 py-2 bg-white border-b d-flex flex-wrap align-center justify-space-between gap-2">
            <div class="d-flex align-center flex-wrap gap-2">
              <v-checkbox
                v-model="selectAll"
                density="compact"
                hide-details
                color="primary"
                @change="toggleSelectAll"
              >
                <template #label>
                  <span class="text-caption font-weight-bold text-slate-800">
                    {{ selectedCount }} of {{ mappedItems.length }} selected
                  </span>
                </template>
              </v-checkbox>

              <v-btn
                size="small"
                variant="outlined"
                color="primary"
                class="ms-2 font-weight-medium"
                prepend-icon="mdi-check-all"
                @click="matchExactAll"
              >
                Select Exact Matches
              </v-btn>
              <v-btn
                size="small"
                variant="outlined"
                color="secondary"
                class="font-weight-medium"
                prepend-icon="mdi-plus-box-multiple-outline"
                @click="setAllUnmatchedToCreateNew"
              >
                Create All Unmatched as New
              </v-btn>
            </div>

            <!-- Filter Search -->
            <v-text-field
              v-model="searchFilter"
              placeholder="Filter by Value, Footprint, Ref..."
              prepend-inner-icon="mdi-magnify"
              density="compact"
              variant="outlined"
              hide-details
              clearable
              rounded="lg"
              style="max-width: 320px;"
            />
          </div>

          <!-- Mapping Table -->
          <div class="flex-grow-1 overflow-y-auto">
            <v-table density="comfortable" hover class="mapping-table">
              <thead>
                <tr class="bg-slate-50">
                  <th style="width: 40px;" class="text-center">#</th>
                  <th class="text-left font-weight-bold" style="width: 250px;">iBOM Part & Footprint</th>
                  <th class="text-center font-weight-bold" style="width: 50px;">Qty</th>
                  <th class="text-left font-weight-bold" style="width: 120px;">Status</th>
                  <th class="text-left font-weight-bold">Target Database Component and package</th>
                  <th class="text-center font-weight-bold" style="width: 140px;">Action</th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="(item, idx) in filteredItems"
                  :key="item.index"
                  :class="{ 'bg-blue-50': item.selected && item.createAsNew, 'opacity-50': !item.selected }"
                >
                  <!-- Selection Checkbox -->
                  <td class="text-center">
                    <v-checkbox
                      v-model="item.selected"
                      density="compact"
                      hide-details
                      color="primary"
                    />
                  </td>

                  <!-- iBOM Part Details -->
                  <td>
                    <div class="font-mono font-weight-bold text-slate-900 text-body-2">
                      {{ item.value || '(No Value)' }}
                    </div>
                    <div class="d-flex align-center gap-1 mt-0.5">
                      <v-chip
                        size="x-small"
                        color="slate-700"
                        variant="tonal"
                        class="font-mono font-weight-medium"
                        :title="`Full Footprint: ${item.footprint}`"
                      >
                        {{ item.cleanedFootprint || item.footprint }}
                      </v-chip>
                      <v-chip
                        v-if="item.suggestedCategory"
                        size="x-small"
                        color="secondary"
                        variant="tonal"
                      >
                        {{ item.suggestedCategory }}
                      </v-chip>
                    </div>
                    <div class="text-caption text-primary font-mono text-truncate mt-1" :title="item.designators" style="max-width: 240px;">
                      {{ item.designators }}
                    </div>
                    <div v-if="item.mpn" class="text-caption text-success font-weight-medium text-truncate" :title="`MPN: ${item.mpn}`" style="max-width: 240px;">
                      MPN: {{ item.mpn }}
                    </div>
                  </td>

                  <!-- Quantity -->
                  <td class="text-center font-mono font-weight-bold text-body-2">
                    {{ item.quantity }}
                  </td>

                  <!-- Mapping Status Chip -->
                  <td>
                    <v-chip
                      v-if="item.createAsNew"
                      size="x-small"
                      color="primary"
                      variant="flat"
                      class="font-weight-bold"
                    >
                      <v-icon start size="12">mdi-plus-circle-outline</v-icon>
                      New Part
                    </v-chip>
                    <v-chip
                      v-else-if="item.matchConfidence === 'exact'"
                      size="x-small"
                      color="success"
                      variant="flat"
                      class="font-weight-bold"
                    >
                      <v-icon start size="12">mdi-check-circle-outline</v-icon>
                      Exact Match
                    </v-chip>
                    <v-chip
                      v-else-if="item.matchConfidence === 'suggested'"
                      size="x-small"
                      color="amber-darken-3"
                      variant="tonal"
                      class="font-weight-bold"
                    >
                      <v-icon start size="12">mdi-lightbulb-outline</v-icon>
                      Suggested
                    </v-chip>
                    <v-chip
                      v-else
                      size="x-small"
                      color="slate-500"
                      variant="tonal"
                      class="font-weight-bold"
                    >
                      Unmapped
                    </v-chip>
                  </td>

                  <!-- Database Target Component Selection & Package Badge -->
                  <td>
                    <div class="py-1">
                      <!-- Unified Clean Text Field Box (No action icons inside) -->
                      <div
                        class="comp-box-outlined d-flex align-center justify-space-between px-3"
                        @click="item.createAsNew ? openNewCompModal(item) : openPickerFor(item)"
                        :title="item.createAsNew ? 'Click to configure and add new component to catalog' : 'Click to map or change database component'"
                      >
                        <!-- Left: Component Name -->
                        <div class="d-flex align-center gap-2 text-truncate me-2">
                          <span
                            class="font-mono font-weight-bold text-truncate"
                            :class="getDisplayComponentName(item) ? 'text-slate-900' : 'text-slate-400 italic'"
                          >
                            {{ getDisplayComponentName(item) || 'Click to select component...' }}
                          </span>
                        </div>

                        <!-- Right: Package Chip aligned to right border -->
                        <div class="flex-shrink-0 ms-auto">
                          <v-chip
                            v-if="getDisplayPackageName(item)"
                            size="x-small"
                            :color="item.createAsNew ? 'indigo' : 'primary'"
                            variant="tonal"
                            class="font-mono font-weight-bold"
                          >
                            {{ getDisplayPackageName(item) }}
                          </v-chip>
                        </div>
                      </div>
                    </div>
                  </td>

                  <!-- Action Column (+, clone, and magnify glass, matching style) -->
                  <td class="text-center">
                    <div class="d-flex align-center justify-center gap-1">
                      <!-- Map to existing component button (magnify glass) -->
                      <v-tooltip text="Map to existing component" location="top">
                        <template #activator="{ props: tipProps }">
                          <v-btn
                            v-bind="tipProps"
                            icon="mdi-magnify"
                            size="small"
                            variant="tonal"
                            color="slate-700"
                            class="flex-shrink-0"
                            @click="openPickerFor(item)"
                          />
                        </template>
                      </v-tooltip>

                      <!-- Clone existing component to map (copy icon) -->
                      <v-tooltip text="Find & clone existing component to map" location="top">
                        <template #activator="{ props: tipProps }">
                          <v-btn
                            v-bind="tipProps"
                            icon="mdi-content-copy"
                            size="small"
                            variant="tonal"
                            color="indigo"
                            class="flex-shrink-0"
                            @click="openClonePickerFor(item)"
                          />
                        </template>
                      </v-tooltip>

                      <!-- Add new button (+) -->
                      <v-tooltip text="Add new" location="top">
                        <template #activator="{ props: tipProps }">
                          <v-btn
                            v-bind="tipProps"
                            icon="mdi-plus"
                            size="small"
                            variant="tonal"
                            color="primary"
                            class="flex-shrink-0"
                            @click="openNewCompModal(item)"
                          />
                        </template>
                      </v-tooltip>
                    </div>
                  </td>
                </tr>
              </tbody>
            </v-table>
          </div>
        </div>
      </v-card-text>

      <!-- Dialog Footer Actions -->
      <v-card-actions class="px-5 py-3 border-t bg-slate-50 d-flex align-center justify-space-between flex-shrink-0">
        <div>
          <v-btn
            v-if="currentStep === 2"
            variant="text"
            size="small"
            prepend-icon="mdi-arrow-left"
            @click="currentStep = 1"
          >
            Back to File Selection
          </v-btn>
        </div>

        <div class="d-flex align-center gap-2">
          <v-btn variant="outlined" size="small" @click="closeDialog">
            Cancel
          </v-btn>

          <v-btn
            v-if="currentStep === 2"
            color="primary"
            variant="flat"
            size="small"
            class="font-weight-bold"
            prepend-icon="mdi-database-import-outline"
            :loading="importing"
            :disabled="selectedCount === 0"
            @click="executeImport"
          >
            Import {{ selectedCount }} Components into BOM
          </v-btn>
        </div>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <!-- Component Picker Re-using AddComponentDialog -->
  <AddComponentDialog
    v-model="pickerDialogOpen"
    :picker-mode="true"
    :clone-mode-only="isClonePickerMode"
    :title="pickerTitle"
    :subtitle="pickerSubtitle"
    :initial-search="pickerInitialSearch"
    :initial-categories="pickerInitialCategories"
    :initial-packages="pickerInitialPackages"
    @select="onComponentPicked"
    @clone="onComponentToClonePicked"
  />

  <!-- RE-USE CREATE COMPONENT DIALOG TO ADD NEW COMPONENT -->
  <CreateComponentDialog
    v-model="createCompDialogOpen"
    :categories="categoryOptions"
    :packages="packageOptions"
    :component="activeCloneCompSource"
    :initial-data="activeNewCompData"
    :is-clone="isCloneMode"
    :title="newCompDialogTitle"
    :subtitle="newCompDialogSubtitle"
    :hide-add-another="true"
    @created="onNewComponentCreated"
  />
</template>

<script setup>
import { ref, computed, watch, onMounted } from 'vue';
import { api } from '../services/api';
import AddComponentDialog from './AddComponentDialog.vue';
import CreateComponentDialog from './CreateComponentDialog.vue';

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false
  },
  projectId: {
    type: Number,
    required: true
  },
  projectName: {
    type: String,
    default: ''
  },
  initialFile: {
    type: Object,
    default: null
  },
  projectFiles: {
    type: Array,
    default: () => []
  }
});

const emit = defineEmits(['update:modelValue', 'bom-imported']);

const currentStep = ref(1);
const parsing = ref(false);
const importing = ref(false);
const parseResult = ref(null);

// Step 1 state
const uploadFile = ref(null);
const selectedAttachmentId = ref(null);

// Step 2 state
const importMode = ref('append');
const mappedItems = ref([]);
const searchFilter = ref('');
const selectAll = ref(true);

// Catalog reference data
const catalogComponents = ref([]);
const categoryOptions = ref([]);
const packageOptions = ref([]);

// Picker state (re-using AddComponentDialog)
const pickerDialogOpen = ref(false);
const isClonePickerMode = ref(false);
const activeMapItem = ref(null);
const pickerInitialSearch = ref('');
const pickerInitialCategories = ref([]);
const pickerInitialPackages = ref([]);

// Configure New Component Modal state (re-using CreateComponentDialog)
const createCompDialogOpen = ref(false);
const isCloneMode = ref(false);
const activeCloneCompSource = ref(null);
const activeNewCompItem = ref(null);
const activeNewCompItemIndex = ref(null);
const activeNewCompData = ref(null);
const newCompDialogTitle = ref('Add New Component');
const newCompDialogSubtitle = ref('');

const pickerTitle = computed(() => {
  if (isClonePickerMode.value) {
    return `Find Component to Clone for ${activeMapItem.value?.value || 'iBOM Part'}`;
  }
  return `Map Component for ${activeMapItem.value?.value || 'iBOM Part'}`;
});

const pickerSubtitle = computed(() => {
  if (!activeMapItem.value) return '';
  return `Row #${activeMapItem.value.index} · Footprint: ${activeMapItem.value.cleanedFootprint || activeMapItem.value.footprint} · Qty: ${activeMapItem.value.quantity}`;
});

// Map of components by ID for O(1) lookups
const componentMap = computed(() => {
  const map = new Map();
  catalogComponents.value.forEach(c => {
    const id = Number(c.ID || c.id);
    if (!isNaN(id)) {
      map.set(id, c);
    }
  });
  return map;
});

function getPackageName(pkgId) {
  if (!pkgId) return '';
  const pkg = packageOptions.value.find(p => p.ID === pkgId);
  return pkg ? pkg.package : '';
}

function getCategoryName(catId) {
  if (!catId) return '';
  const cat = categoryOptions.value.find(c => c.ID === catId);
  return cat ? cat.category : '';
}

function suggestedPackageName(item) {
  if (!item) return '';
  if (item.newCompData?.package_id) {
    const pkg = getPackageName(item.newCompData.package_id);
    if (pkg && pkg.toLowerCase() !== 'unknown') return pkg;
  }
  return item.suggestedPackage || item.cleanedFootprint || item.footprint || '';
}

function compPackageName(raw) {
  if (!raw) return '';
  if (raw.package && raw.package.toLowerCase() !== 'unknown') return raw.package;
  if (raw.package_id) {
    const pkg = getPackageName(raw.package_id);
    if (pkg && pkg.toLowerCase() !== 'unknown') return pkg;
  }
  return raw.package || '';
}

function getDisplayComponentName(item) {
  if (!item) return '';
  if (item.createAsNew) {
    return item.newCompData?.component || item.value || '';
  }
  if (item.selectedComponentId) {
    const comp = componentMap.value.get(Number(item.selectedComponentId)) || item.matchedComponent;
    if (comp) return comp.component;
  }
  if (item.matchedComponent) {
    return item.matchedComponent.component;
  }
  return item.value || '';
}

function getDisplayPackageName(item) {
  if (!item) return '';
  if (item.createAsNew) {
    return suggestedPackageName(item);
  }
  if (item.selectedComponentId) {
    const comp = componentMap.value.get(Number(item.selectedComponentId)) || item.matchedComponent;
    if (comp) return compPackageName(comp) || getPackageName(comp.package_id);
  }
  if (item.matchedComponent) {
    return compPackageName(item.matchedComponent) || getPackageName(item.matchedComponent.package_id);
  }
  return item.suggestedPackage || item.cleanedFootprint || item.footprint || '';
}

function unmapRowToNewPart(item) {
  item.selectedComponentId = null;
  item.matchedComponent = null;
  item.createAsNew = true;
  item.matchConfidence = 'unmatched';
  item.matchReason = 'Configured as new part';
}

// Filter attached files to only iBOM or HTML files
const ibomAttachments = computed(() => {
  return (props.projectFiles || []).filter(f => {
    const isIbomType = f.fileType === 'ibom';
    const isHtml = (f.originalName || '').toLowerCase().endsWith('.html') || (f.originalName || '').toLowerCase().endsWith('.htm');
    return isIbomType || isHtml;
  });
});

const selectedCount = computed(() => {
  return mappedItems.value.filter(it => it.selected).length;
});

const filteredItems = computed(() => {
  if (!searchFilter.value || !searchFilter.value.trim()) {
    return mappedItems.value;
  }
  const q = searchFilter.value.toLowerCase().trim();
  return mappedItems.value.filter(it => {
    return (it.value || '').toLowerCase().includes(q) ||
           (it.footprint || '').toLowerCase().includes(q) ||
           (it.cleanedFootprint || '').toLowerCase().includes(q) ||
           (it.designators || '').toLowerCase().includes(q) ||
           (it.mpn || '').toLowerCase().includes(q);
  });
});

// Custom filter for components autocomplete
function componentFilter(itemTitle, queryText, item) {
  if (!queryText) return true;
  const q = queryText.toLowerCase();
  const c = item.raw;
  return (c.component || '').toLowerCase().includes(q) ||
         (c.marking || '').toLowerCase().includes(q) ||
         (c.package || '').toLowerCase().includes(q) ||
         (c.shortDescription || '').toLowerCase().includes(q);
}

// Watch initialFile or modelValue opening
watch(() => props.modelValue, (isOpen) => {
  if (isOpen) {
    loadCatalogData();
    if (props.initialFile) {
      selectedAttachmentId.value = props.initialFile.id;
      parseSelectedAttachment();
    } else if (ibomAttachments.value.length > 0) {
      selectedAttachmentId.value = ibomAttachments.value[0].id;
    }
  } else {
    resetDialog();
  }
});

async function loadCatalogData() {
  try {
    const [comps, cats, pkgs] = await Promise.all([
      api.getComponents({ limit: 5000 }),
      api.getCategories(),
      api.getPackages()
    ]);
    catalogComponents.value = comps?.items || (Array.isArray(comps) ? comps : []);
    categoryOptions.value = Array.isArray(cats) ? cats : (cats?.items || []);
    packageOptions.value = Array.isArray(pkgs) ? pkgs : (pkgs?.items || []);
  } catch (err) {
    console.error('Failed to load catalog data:', err);
  }
}

function resetDialog() {
  currentStep.value = 1;
  parsing.value = false;
  importing.value = false;
  parseResult.value = null;
  uploadFile.value = null;
  mappedItems.value = [];
  searchFilter.value = '';
  activeMapItem.value = null;
  isClonePickerMode.value = false;
  isCloneMode.value = false;
  activeCloneCompSource.value = null;
  activeNewCompItem.value = null;
  activeNewCompItemIndex.value = null;
  activeNewCompData.value = null;
}

function closeDialog() {
  emit('update:modelValue', false);
}

async function parseSelectedAttachment() {
  if (!selectedAttachmentId.value || !props.projectId) return;
  parsing.value = true;
  try {
    const res = await api.parseIbom(props.projectId, { fileId: selectedAttachmentId.value });
    initMappedItems(res);
  } catch (err) {
    console.error('Error parsing iBOM file:', err);
    alert(err.response?.data?.details || err.response?.data?.error || err.message || 'Failed to parse iBOM file');
  } finally {
    parsing.value = false;
  }
}

async function parseUploadedFile() {
  if (!uploadFile.value || !props.projectId) return;
  const fileObj = Array.isArray(uploadFile.value) ? uploadFile.value[0] : uploadFile.value;
  if (!fileObj) return;

  parsing.value = true;
  try {
    const formData = new FormData();
    formData.append('file', fileObj);
    const res = await api.parseIbom(props.projectId, formData, true);
    initMappedItems(res);
  } catch (err) {
    console.error('Error parsing uploaded iBOM:', err);
    alert(err.response?.data?.details || err.response?.data?.error || err.message || 'Failed to parse iBOM file');
  } finally {
    parsing.value = false;
  }
}

function initMappedItems(data) {
  parseResult.value = data;
  mappedItems.value = (data.items || []).map(item => {
    const hasMatch = !!item.matchedComponent;
    const selectedComponentId = hasMatch ? item.matchedComponent.ID : null;

    return {
      ...item,
      selected: true,
      createAsNew: !hasMatch,
      selectedComponentId,
      comment: item.designators || '',
      newCompData: {
        component: item.mpn || item.value || 'New Component',
        category_id: item.suggestedCategoryId || null,
        package_id: item.suggestedPackageId || (packageOptions.value.find(p => p.package.toLowerCase() === 'unknown')?.ID || 1),
        marking: item.value || '',
        description: item.extra?.Description || `${item.value} ${item.cleanedFootprint || ''}`.trim(),
        shortDescription: item.value || '',
        qty: 0
      }
    };
  });
  currentStep.value = 2;
}

// Open Component Picker (re-using AddComponentDialog)
function openPickerFor(item) {
  activeMapItem.value = item;
  isClonePickerMode.value = false;
  pickerInitialSearch.value = item.value || item.mpn || '';
  pickerInitialCategories.value = item.suggestedCategoryId ? [item.suggestedCategoryId] : [];
  pickerInitialPackages.value = item.suggestedPackageId ? [item.suggestedPackageId] : [];
  pickerDialogOpen.value = true;
}

// Open Component Picker in Clone Mode
function openClonePickerFor(item) {
  activeMapItem.value = item;
  isClonePickerMode.value = true;
  pickerInitialSearch.value = item.value || item.mpn || '';
  pickerInitialCategories.value = item.suggestedCategoryId ? [item.suggestedCategoryId] : [];
  pickerInitialPackages.value = item.suggestedPackageId ? [item.suggestedPackageId] : [];
  pickerDialogOpen.value = true;
}

// Callback when user picks a component from AddComponentDialog
function onComponentPicked(comp) {
  if (!activeMapItem.value || !comp) return;

  activeMapItem.value.selectedComponentId = comp.ID;
  activeMapItem.value.createAsNew = false;
  activeMapItem.value.matchConfidence = 'exact';
  activeMapItem.value.matchReason = 'Manually selected';

  // Make sure the component is in catalogComponents list for autocomplete dropdown
  if (!catalogComponents.value.some(c => c.ID === comp.ID)) {
    catalogComponents.value.unshift(comp);
  }

  pickerDialogOpen.value = false;
  activeMapItem.value = null;
}

// Callback when user picks a component to clone as a template
function onComponentToClonePicked(comp) {
  if (!activeMapItem.value || !comp) return;

  const targetItem = activeMapItem.value;
  activeNewCompItem.value = targetItem;
  activeNewCompItemIndex.value = targetItem.index;

  const normVal = targetItem.normalizedValue || targetItem.value || '';
  const cleanFp = targetItem.cleanedFootprint || targetItem.footprint || '';

  activeCloneCompSource.value = comp;
  isCloneMode.value = true;

  activeNewCompData.value = {
    component: targetItem.mpn || targetItem.value || `${comp.component} (Copy)`,
    category_id: comp.category_id || targetItem.suggestedCategoryId || null,
    package_id: comp.package_id || targetItem.suggestedPackageId || (packageOptions.value.find(p => p.package.toLowerCase() === 'unknown')?.ID || 28),
    marking: targetItem.value || comp.marking || '',
    shortDescription: (normVal && cleanFp) ? `${normVal} ${cleanFp}`.trim() : (comp.shortDescription || ''),
    description: comp.description || (targetItem.designators ? `KiCAD Designators: ${targetItem.designators}` : ''),
    qty: 0,
    minQty: comp.minQty || 0,
    storageId: comp.storageId || comp.storage_id || comp.warehouse?.[0]?.storageId || null,
    datasheetURL: comp.datasheetURL || '',
    photoURL: comp.photoURL || ''
  };

  newCompDialogTitle.value = `Clone & Map Component (BOM Row #${targetItem.index})`;
  newCompDialogSubtitle.value = `Cloning "${comp.component}" for "${targetItem.value || 'Part'}" (${targetItem.quantity} pcs · Footprint: ${cleanFp || 'Unknown'})`;

  pickerDialogOpen.value = false;
  createCompDialogOpen.value = true;
}

// Open modal to configure/create a new component
function openNewCompModal(item) {
  activeCloneCompSource.value = null;
  isCloneMode.value = false;
  activeNewCompItem.value = item;
  activeNewCompItemIndex.value = item.index;
  const normVal = item.normalizedValue || item.value || '';
  const cleanFp = item.cleanedFootprint || item.footprint || '';

  activeNewCompData.value = {
    component: item.newCompData?.component || item.mpn || item.value || '',
    category_id: item.newCompData?.category_id || item.suggestedCategoryId || null,
    package_id: item.newCompData?.package_id || item.suggestedPackageId || (packageOptions.value.find(p => p.package.toLowerCase() === 'unknown')?.ID || 28),
    marking: item.newCompData?.marking || item.value || '',
    shortDescription: item.newCompData?.shortDescription || (normVal ? `${normVal} ${cleanFp}`.trim() : ''),
    description: item.newCompData?.description || (item.designators ? `KiCAD Designators: ${item.designators}` : ''),
    qty: item.newCompData?.qty !== undefined ? item.newCompData.qty : 0,
    storageId: item.newCompData?.storageId || null,
    datasheetURL: item.newCompData?.datasheetURL || '',
    photoURL: item.newCompData?.photoURL || ''
  };
  newCompDialogTitle.value = `Add New Component (BOM Row #${item.index})`;
  newCompDialogSubtitle.value = `Create a catalog component for "${item.value || item.mpn || 'Part'}" (${item.quantity} pcs · Footprint: ${cleanFp || 'Unknown'})`;
  createCompDialogOpen.value = true;
}

function onNewComponentCreated(newComp) {
  if (!newComp) return;

  const compId = Number(newComp.ID || newComp.id);
  const fullCompObj = {
    ...newComp,
    ID: compId,
    id: compId,
    package: newComp.package || getPackageName(newComp.package_id),
    category: newComp.category || getCategoryName(newComp.category_id)
  };

  // Ensure new component is available in catalogComponents
  const existingIdx = catalogComponents.value.findIndex(c => Number(c.ID || c.id) === compId);
  if (existingIdx === -1) {
    catalogComponents.value.unshift(fullCompObj);
  } else {
    catalogComponents.value[existingIdx] = fullCompObj;
  }

  // Find target row item by index or reference
  const targetIndex = activeNewCompItemIndex.value;
  const targetItem = mappedItems.value.find(it => it.index === targetIndex) || activeNewCompItem.value;

  if (targetItem) {
    targetItem.selectedComponentId = compId;
    targetItem.matchedComponent = fullCompObj;
    targetItem.matchConfidence = 'exact';
    targetItem.matchReason = isCloneMode.value
      ? `Cloned from ${activeCloneCompSource.value?.component || 'catalog'}`
      : 'Created new component';
    targetItem.createAsNew = false;
    targetItem.selected = true;

    // Auto-suggest to other unmapped rows with identical value and footprint
    const rowVal = (targetItem.value || '').trim().toLowerCase();
    const rowFp = (targetItem.cleanedFootprint || targetItem.footprint || '').trim().toLowerCase();
    if (rowVal) {
      mappedItems.value.forEach(other => {
        if (other !== targetItem && !other.selectedComponentId) {
          const otherVal = (other.value || '').trim().toLowerCase();
          const otherFp = (other.cleanedFootprint || other.footprint || '').trim().toLowerCase();
          if (otherVal === rowVal && (!rowFp || !otherFp || rowFp === otherFp)) {
            other.selectedComponentId = compId;
            other.matchedComponent = fullCompObj;
            other.matchConfidence = 'suggested';
            other.matchReason = 'Matches newly created component';
            other.createAsNew = false;
            other.selected = true;
          }
        }
      });
    }
  }

  createCompDialogOpen.value = false;
  activeNewCompItem.value = null;
  activeNewCompItemIndex.value = null;
  activeNewCompData.value = null;
  activeCloneCompSource.value = null;
  isCloneMode.value = false;
}

function toggleSelectAll() {
  const target = selectAll.value;
  mappedItems.value.forEach(it => {
    it.selected = target;
  });
}

function matchExactAll() {
  mappedItems.value.forEach(it => {
    if (it.matchedComponent) {
      it.selected = true;
      it.createAsNew = false;
      it.selectedComponentId = it.matchedComponent.ID;
    } else {
      it.selected = false;
    }
  });
}

function setAllUnmatchedToCreateNew() {
  mappedItems.value.forEach(it => {
    if (!it.matchedComponent && !it.selectedComponentId) {
      it.createAsNew = true;
      it.selected = true;
    }
  });
}

async function executeImport() {
  const selectedItems = mappedItems.value.filter(it => it.selected);
  if (selectedItems.length === 0) return;

  importing.value = true;
  try {
    const payloadItems = selectedItems.map(it => {
      if (it.createAsNew) {
        return {
          createAsNew: true,
          newComponent: it.newCompData,
          quantity: it.quantity,
          comment: it.comment
        };
      } else {
        return {
          createAsNew: false,
          componentId: it.selectedComponentId || it.matchedComponent?.ID,
          quantity: it.quantity,
          comment: it.comment
        };
      }
    });

    const result = await api.importIbom(props.projectId, {
      mode: importMode.value,
      items: payloadItems
    });

    emit('bom-imported', result);
    closeDialog();
  } catch (err) {
    console.error('Failed to import BOM:', err);
    alert(err.response?.data?.details || err.response?.data?.error || err.message || 'Failed to import BOM');
  } finally {
    importing.value = false;
  }
}

onMounted(() => {
  if (props.modelValue) {
    loadCatalogData();
  }
});
</script>

<style scoped>
.mapping-table :deep(tr:hover) {
  background-color: #f8fafc !important;
}

.bg-blue-50 {
  background-color: #eff6ff !important;
}

.bg-slate-50 {
  background-color: #f8fafc !important;
}

.border-b {
  border-bottom: 1px solid #e2e8f0 !important;
}

.border-t {
  border-top: 1px solid #e2e8f0 !important;
}

.comp-box-outlined {
  height: 40px;
  min-height: 40px;
  background-color: #f8fafc;
  border: 1px solid rgba(0, 0, 0, 0.38);
  border-radius: 8px;
  cursor: pointer;
  box-sizing: border-box;
  transition: all 0.15s ease-in-out;
}

.comp-box-outlined:hover {
  background-color: #f1f5f9;
  border-color: #1976d2;
}

.autocomplete-menu-item {
  width: 100% !important;
}

.autocomplete-menu-item :deep(.v-list-item__content) {
  width: 100% !important;
  min-width: 0 !important;
  display: flex !important;
  flex-direction: column !important;
}
</style>
